INSERT INTO TOUR (NAME, PRICE, DURATION, TRANSFER) VALUES ('Turkey', 1256, 14, 'BELAVIA');
INSERT INTO TOUR (NAME, PRICE, DURATION, TRANSFER) VALUES ('Paris', 2256, 10, 'AIRFARNCE');
INSERT INTO TOUR (NAME, PRICE, DURATION, TRANSFER) VALUES ('Murmansk', 956, 7, 'AEROFLOT');
INSERT INTO TOUR (NAME, PRICE, DURATION, TRANSFER) VALUES ('Hong Kong', 3956, 12, 'EMIRATES');
INSERT INTO TOUR (NAME, PRICE, DURATION, TRANSFER) VALUES ('Cape Town', 5853, 17, 'BELAVIA');